name: CD Pipeline - Deploy to Render

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Start Deployment
        run: echo "CI successful. Starting CD pipeline..."

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Latest Docker Image
        run: docker pull sarammalik0010/uni-notice-board:latest

      - name: Trigger Render Deployment
        run: |
          curl -X POST "${{ secrets.RENDER_CALLBACK_URL }}"

      - name: Deployment Completed
        run: echo "Deployment to Render triggered successfully"
